services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Setup Commands
    BetterAuth\Symfony\Command\SetupLoggingCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
        tags:
            - { name: 'console.command' }

    BetterAuth\Symfony\Command\SetupDependenciesCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
        tags:
            - { name: 'console.command' }

    BetterAuth\Symfony\Command\UpdateConfigCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
        tags:
            - { name: 'console.command' }

    # Feature Setup Command
    BetterAuth\Symfony\Command\SetupFeaturesCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
        tags:
            - { name: 'console.command' }

    # Existing commands
    BetterAuth\Symfony\Command\InstallCommand:
        tags:
            - { name: 'console.command' }

    # Configuration Commands
    BetterAuth\Symfony\Command\SwitchModeCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
        tags:
            - { name: 'console.command' }

    BetterAuth\Symfony\Command\GenerateConfigCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
        tags:
            - { name: 'console.command' }

    BetterAuth\Symfony\Command\ConfigureCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
        tags:
            - { name: 'console.command' }

    # Cleanup Commands
    BetterAuth\Symfony\Command\CleanupSessionsCommand:
        tags:
            - { name: 'console.command' }

    BetterAuth\Symfony\Command\CleanupTokensCommand:
        tags:
            - { name: 'console.command' }

    # Utility Commands
    BetterAuth\Symfony\Command\PublishTemplatesCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
        tags:
            - { name: 'console.command' }

    BetterAuth\Symfony\Command\GenerateSecretCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
        tags:
            - { name: 'console.command' }

    # Controller Management Commands
    BetterAuth\Symfony\Command\AddControllerCommand:
        tags:
            - { name: 'console.command' }

    BetterAuth\Symfony\Command\UserFieldsCommand:
        tags:
            - { name: 'console.command' }
